version: '2'

services:
  app:
    image: 'akisali/address-book:latest'
# Uncomment to build local image
#    build:
#      context: .
    container_name: app
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/address_book
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: 'postgres:13.4-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=address_book